### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by wencan** [eNkru/freechat#28]
Segmentation fault
version: 0.1.1
os: Linux skynet 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by eNkru** [comment]
need more information.

is the error occurred during your build, run or it's happening when you run the downloaded appimage?

Normally this occurs when you have old version of npm or node and try to build the package.

**Comment by wencan** [comment]
我使用的是github上下载的最新AppImage文件
没安装npm和node

**Comment by eNkru** [comment]
我估计是不兼容的GLIB版本导致，最好的办法是你安装一个node.js 8+ & yarn，然后按照README的步骤自己build一份。然后dist目录下的appimage就是你可以运行的版本了。

build之前可以先运行`yarn start`看可不可以使用

**Comment by svnwell** [comment]
我也是使用appimage遇到了 Segmentation fault问题。源码编译是没问题的。 @eNkru @wencan

**Comment by svnwell** [comment]
> 我也是使用appimage遇到了 Segmentation fault问题。源码编译是没问题的。 @eNkru @wencan

我的系统版本是 fedora30

**Comment by eNkru** [comment]
应该是那个RELEASE的BUILD太老了，毕竟也过了很久拉

**Comment by eNkru** [comment]
等我有时间BUILD一个新版本把

**Comment by eNkru** [comment]
试一下这个版本会不会还有问题

https://github.com/eNkru/freechat/releases/tag/v1.0.0
