### ISSUE TITLE
微信登录后页面显示不全

### ISSUE THREAD

**Issue by omaidb** [eNkru/freechat#31]
登录只显示了左侧很小的一块，联系人都显示不全，只有手机屏幕的宽度，而且无法拉伸。

**Comment by eNkru** [comment]
这个问题是因为你的登录域名和别人的不太一样，程序无法检测到你的登录事件。
你能用网页版登录一下，看看你的NETWORK的TRAFFIC里面关于下面两个的域名是什么吗？

登录后会有这个请求
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxinit

登出后会有这个
https://wx.qq.com/?&lang

你的应该不是wx.qq.com, 能告诉我是什么吗？

暂时的解决方案就是把登录窗口变成可以RESIZE的，这样登录后你可以自己拖拽窗口大小。

**Comment by eNkru** [comment]
暂时的解决办法

https://github.com/eNkru/electron-wechat/commit/ebfdcf09b8db193dfb9a29b00f6f5d03ed9960e3

**Comment by eNkru** [comment]
https://github.com/eNkru/freechat/releases/tag/v1.0.0

暂时修复了问题，你可以自己RESIZE窗口大小
