### ISSUE TITLE
没有反应

### ISSUE THREAD

**Issue by dreamer-otw** [eNkru/freechat#35]
下载 .deb文件安装后，点击图标，没有反应

**Comment by dreamer-otw** [comment]
系统版本 debian10.1

**Comment by eNkru** [comment]
你试试那个AppImage吧，比较通用。现在手上没有DEBIAN系统。如果谁在用DEBIAN的话，可以帮忙调试一下？

**Comment by dreamer-otw** [comment]
ok，我看一下

**Comment by thesomeexp** [comment]
解决了吗?同Debian10运行没反应.

**Comment by eNkru** [comment]
deb的包应该是很早以前打包的。appimage的比较通用。
另外如果能设置好开发环境的话，自己build一个比较理想

**Comment by eNkru** [comment]
现在没有再用debian或者ubuntu了，可能打包的deb不兼容。使用appimage吧
