### ISSUE TITLE
Where's the PlayerController definition?

### ISSUE THREAD

**Issue by universeroc** [eNkru/freechat#39]
https://github.com/eNkru/freechat/blob/502ab8ca6c04a421ed5439715ca0eca0af0b1b96/src/main.js#L59

Maybe the PlayerController is an old one but discard in current design, in your controllers directory there's only main and app tray controller.

**Comment by eNkru** [comment]
This is a bug get copied from another project. lol

as the logic only for macOS, so might not been detected.

it should be `new MainController()`

**Comment by eNkru** [comment]
it's been fixed in master branch
