### ISSUE TITLE
现在网页版限制登录了，请问该项目还能使用吗？

### ISSUE THREAD

**Issue by KoapT** [eNkru/freechat#40]

**Comment by eNkru** [comment]
如果你的账号被网页版限制了，这个也没办法。这个软件的核心还是基于网页版的。

老的微信账号还是没问题吧？

**Comment by KoapT** [comment]
> 
> 
> 如果你的账号被网页版限制了，这个也没办法。这个软件的核心还是基于网页版的。
> 
> 老的微信账号还是没问题吧？

我微信用了7 8 年了，以前是可以登网页版的，不知道啥时候被限制了。。 只能虚拟机了。

**Comment by eNkru** [comment]
有听说过这个，是不是之前在网页版上面多开了？

我身边的微信都还是可以登录的。

如果网页版限制了你的登录，这个也没什么太好的办法，因为都是基于网页版的 ：（

**Comment by KoapT** [comment]
> 有听说过这个，是不是之前在网页版上面多开了？
> 
> 我身边的微信都还是可以登录的。
> 
> 如果网页版限制了你的登录，这个也没什么太好的办法，因为都是基于网页版的 ：（

谢谢回复～
