### ISSUE TITLE
ArchLinux 通过 yay 下载卡在 electron downloading

### ISSUE THREAD

**Issue by JohnNiang** [eNkru/freechat#48]
模拟 `yay` 安装的打包步骤：

```node
➜  freechat-1.0.0 git:(master) ✗ proxychains -q npm run pack

> electron-wechat@1.0.0 pack /home/johnniang/.cache/yay/electron-wechat/src/freechat
> electron-builder --dir

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=9.0.1 appOutDir=dist/linux-unpa
  • downloading     parts=8 size=74 MB url=https://github.com/electron/electron/relex64.zip
```

`electron` 版本：

```bash
➜  ~ electron -v
v9.0.1
```

这是网络问题，我明白。但是 `electron` 已经通过 `pacman` 安装过，并且加上了 `proxychains` 进行代理，npm 依赖倒是很快下载好了，可不太理解为什么还需要重新下载 `electron`，或者有什么办法能够跳过这个步骤么？

**Comment by eNkru** [comment]
我的electron是在run `npm install`的时候安装的。
你看一下`freechat/node_modules/electron`有没有东西，如果有的话，试用`npm run dist:linux` build你的安装包。

**Comment by JohnNiang** [comment]
谢谢您的回复。虽然最后在 `~/.cache/yay/electron-wechat/src/freechat` 用 `proxychains` 将 `electron` 下载成功，但安装完成后因为 icon 的问题无法继续使用。不过可以轻松通过 `npm run start` 使用。
