### ISSUE TITLE
可以考虑一下发布Win的Build吗

### ISSUE THREAD

**Issue by HENUAsshole69** [eNkru/freechat#52]
可以考虑一下发布Win的Build吗，不太喜欢官方的版本

**Comment by eNkru** [comment]
@HENUAsshole69 加入了windows的build脚本 https://github.com/eNkru/freechat/commit/a0f98c05c954e6da60063a9b519a1222b4410898。你如果有装NPM的话，可以自己build一个版本。我现在手上没有可用的windows

```
npm i
npm run dist:win
```
