### ISSUE TITLE
关于利用腾讯UOS客户端接口登录的想法

### ISSUE THREAD

**Issue by JoveYu** [eNkru/freechat#62]
大体看了下所谓原生linux客户端，其实就是web微信的封装，而且封装的及其简陋。

分析uos客户端，发现其中有一个腾讯提供的模块，会获取/etc系统相关信息生成一个token，其他平台用户使用无法直接登录也是这个模块的原因，在web微信调用登录接口的时候传递这个token，系统会识别成为linux用户，有2个最大的区别，1是手机端显示桌面微信登录而不是web微信登录，2是原本无法登录web微信的用户也可以登录了。

可以尝试在抽出这个模块，打包到freechat登录中，那么可以做到真正原生的客户端待遇
@eNkru

**Comment by eNkru** [comment]
我有时间研究一下，应该不是问题
