### ISSUE TITLE
调用UOS版私有接口解决无法登录问题

### ISSUE THREAD

**Issue by JoveYu** [eNkru/freechat#63]
最近听闻微信出了linux版本，发现本质还是web微信，尝试调用UOS版本中隐藏接口成功移植到freechat

arch的朋友可以帮忙测试下  https://aur.archlinux.org/packages/freechat-uos/

**Comment by BlueSky-07** [comment]
用 Docker 把获取 token 这个操作包装了一下，mac 上经测试可以使用：
https://github.com/BlueSky-07/wechat-token

**Comment by eNkru** [comment]
能提交一份PR吗？

**Comment by JoveYu** [comment]
由于使用UOS包中的二进制获取数据，没办法提交代码PR，有能力的朋友帮忙提交个打包PR
