### ISSUE TITLE
登录提示要开启微信支付

### ISSUE THREAD

**Issue by qingchuwudi** [eNkru/freechat#76]
## 情景

- Ubuntu 20.04.2 64位系统
- 用主分支代码启动(npm start)

问题：

扫码登录时提示要开启微信支付才嫩使用。

> 在 release 1.0.0 版本上没有这个问题

![2021-08-24_14-11-35](https://user-images.githubusercontent.com/10055337/130565659-26e2cd1f-f9d7-408a-b29b-84e60c746e5f.png)

**Comment by qingchuwudi** [comment]
看来是没人维护了，计划下周关闭issue。

**Comment by eNkru** [comment]
这个个人没有遇到，可能是我有开微信支付。这个只是一个微信网页版的壳。如果网页版增加了一些限制，这个app也不能改变什么。最近微信把海外用户分流到了wechat上，估计是要分别待遇。以后这种要求可能会越来越多。理解吧，在他们的体制下能用多少算多少了

**Comment by qingchuwudi** [comment]
@eNkru  嗯，不过在 release 1.0.0 版本上没有这个问题，实在不行只能坚持在老版本了。

**Comment by qingchuwudi** [comment]
到期关闭
